name: geo_music_personality
description: 一个基于地理位置生成音乐的人格测试应用

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  webview_flutter: ^4.2.0
  path_provider: ^2.0.15
  audioplayers: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/test.geojson
    - assets/web/tone_engine.html 