name: geo_music_personality
description: 基于地理位置触发音乐与人格测试结果的应用

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  geolocator: ^9.0.2
  audioplayers: ^5.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/test.geojson 